from models.abm.abm import ABM, ABMFeaturizer
from models.abm.pp_functions import update_parental

import numpy as np
import random
import torch
import torch.nn.functional as F
from torch import nn
from torch.optim import Adam
from tqdm.auto import tqdm 
from torch_geometric.nn import MessagePassing
from tqdm import tqdm
from torch_geometric.data import Data, DataLoader


# Utility functions 

def exists(x):
    return x is not None

# Model components definitions

class GNN(MessagePassing):
    def __init__(self, in_channels, out_channels, hidden=[8,16,32],aggregation='add'):
        super().__init__(aggr=aggregation)
        
        self.dims = list(zip(
                    [2 * in_channels] + hidden, # 2 is one local one neighbors
                    hidden + [out_channels])
                        )

        self.layers = nn.ModuleList([])
        for dim_in, dim_out in self.dims:
            self.layers.append(
                nn.Sequential(
                nn.Linear(dim_in,dim_out),
                nn.LeakyReLU(negative_slope=0.1)
                )
            )
               
    def forward(self,x,edge_index):

        messages = self.propagate(edge_index, x=x)
        h = torch.hstack([messages,x])

        for block in self.layers:
            h = block(h)
        return h
    
    def message(self, x_j):
        return x_j

# Defining the whole model + training + sampling

class GNNModel:
    """ GNN-only ablated model. """

    def __init__(self, n_features, abm_featurizer: ABMFeaturizer,aggregation='add'):
        self.abm_featurizer = abm_featurizer
        
        self.abm_featurizer = abm_featurizer
        self.feature_dim = n_features
        self.static_feature_dim = self.abm_featurizer.get_shape_state_features()[0]
        self.state_dim = self.feature_dim + self.static_feature_dim
        self.gnn_hidden_dims = [32,64,128,128,64,32]
        self.lr_gnn = 0.0002
        self.aggregation = aggregation
        self.graph_model = GNN(self.state_dim,self.feature_dim,hidden=self.gnn_hidden_dims,aggregation=aggregation)
        self.optimizer = Adam(self.graph_model.parameters(),lr=self.lr_gnn)
        self.losses = []
        

    def p_losses(self,true_state, predicted_state,loss_type="l2"):

        if loss_type == 'l1':
            loss = F.l1_loss(true_state, predicted_state)
        elif loss_type == 'l2':
            loss = F.mse_loss(true_state, predicted_state)
        elif loss_type == "huber":
            loss = F.smooth_l1_loss(true_state, predicted_state)
        else:
            raise NotImplementedError()

        return loss

    def train(self, ramifications, n_epochs=10):
        """ Train the model using a `ramifications` data set as generated by `generate_ramifications`. """
        
        device = "cuda" if torch.cuda.is_available() else "cpu"
        self.graph_model.to(device)

        preprocessed_data = []  # list of (state_t0, edge_index, state_t1)

        n_timesteps = len(ramifications[1:])
        n_runs = len(ramifications[1])
        for t in range(n_timesteps):
            prev_state = ramifications[t][0]
            edge_index = torch.tensor(self.abm_featurizer.get_interaction_graph(prev_state), dtype=torch.long, device=device)
            state_t0 = torch.tensor(self.abm_featurizer.scale_abm_state(prev_state), dtype=torch.float32, device=device)
            for run in range(n_runs):
                next_state = ramifications[t+1][run]
                state_t1 = torch.tensor(self.abm_featurizer.scale_abm_state(next_state)[:, self.static_feature_dim:], dtype=torch.float32, device=device)
        
                preprocessed_data.append((state_t0, edge_index, state_t1))

        pyg_graphs = []
        for state_t0, edge_index, state_t1 in preprocessed_data:
            data = Data(x=state_t0, edge_index=edge_index, y=state_t1)
            pyg_graphs.append(data)

        loader = DataLoader(pyg_graphs, batch_size=16, shuffle=True)
        
        for epoch in tqdm(range(n_epochs),'Training:'):
            for batch in loader:
                self.optimizer.zero_grad()
                out = self.graph_model(batch.x, batch.edge_index)
                loss = self.p_losses(out, batch.y)
                self.losses.append(loss.item())
                loss.backward()
                self.optimizer.step()
        

    
    @torch.no_grad()
    def next_step_samples(self, state: np.ndarray, seed=42, n_samples=1) -> np.ndarray:
        """ Given a matrix representing the state at t, returns a list of possible outcomes,
            where each element of the list is a matrix representing the state at t+1.
        """
        device = next(self.graph_model.parameters()).device

        edges = torch.tensor(self.abm_featurizer.get_interaction_graph(state)).to(device)
        state_array = self.abm_featurizer.scale_abm_state(state)
        condition = torch.tensor(state_array).to(torch.float32).to(device)
        outputs = []
        for n in range(n_samples):
            output = self.graph_model(condition,edges).cpu().numpy()
            outputs.append(output)
        outputs = np.array(outputs)
        future_states = self.abm_featurizer.unscale_abm_state(outputs)
        return np.array(future_states)


class SimulatedABM_GNN_only(ABM):
    """ Class that takes a trained model and puts into the same interface used by ABM.
    """
    def __init__(self, initial_state: np.ndarray, model: GNNModel):
        self.model = model
        self.initial_state_np = initial_state

    def initial_state(self):
        return self.initial_state_np

    def next_step(self, state: np.ndarray, seed: int) -> np.ndarray:
        """ Given a matrix representing the state at t, 
            returns a matrix representing state at t+1.
        """
        return self.model.next_step_samples(state=state, seed=seed, n_samples=1)[0]
    
    def simulation_schelling(self,simulation_time: int, seed: int) -> np.ndarray:
        n, c = np.shape(self.initial_state_np)
        simulation_array = np.empty((simulation_time,n,c))
        colors = np.expand_dims(self.initial_state_np[:,-1],axis=0).T 
        new_state = self.initial_state_np
        simulation_array[0] = new_state
        for t in range(1,simulation_time): 
            state_variables = self.model.next_step_samples(state=new_state,seed=seed,n_samples=1)[0]
            new_state = np.hstack((state_variables,colors))
            simulation_array[t] = new_state
        
        return simulation_array
    
    def simulation_pp(self,simulation_time: int, seed: int) -> np.ndarray:
        self.initial_state_np = np.delete(self.initial_state_np,7,axis=1)
        n, c = np.shape(self.initial_state_np)
        simulation_array = np.empty((simulation_time,n,c))
        kind = self.initial_state_np[:,0]
        kind_expanded = np.expand_dims(self.initial_state_np[:,0],axis=0).T 
        family = self.initial_state_np[:,-2:]
        new_state = self.initial_state_np
        simulation_array[0] = new_state
        new_seed = seed
        for t in tqdm(range(1,simulation_time),desc='Simulation'): 
            state_variables = self.model.next_step_samples(state=new_state,seed=new_seed,n_samples=1)[0]
            family = update_parental(torch.tensor(family),torch.tensor(kind),torch.tensor(state_variables[:,:4].T)).numpy()
            new_state = np.hstack((kind_expanded,state_variables,family))
            simulation_array[t] = new_state
            new_seed = random.randint(0,10000)
        
        return simulation_array